baseURL = "https://lokal.ninja/oesterreich"
languageCode = "de-DE"
title = "Lokal Ninja - Österreich"
theme = "ln-base"

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML"]

[params]
  org = "lokal-ninja"
  region = "Österreich"
  repo = "oesterreich"
