baseURL = "https://at.shoogle.net/austria"
languageCode = "de"
title = "Österreich"
theme = "ln-base"

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]

[params]
  site = "Lokal Ninja"
  org = "lokal-ninja"
  repo = "austria"
