baseURL = "https://lokal.ninja/oesterreich"
languageCode = "de-DE"
title = "Österreich"
theme = "ln-base"

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML"]

[params]
  site = "Lokal Ninja"
  org = "lokal-ninja"
  repo = "oesterreich"
