baseURL = "https://at.shoogle.net/austria"
languageCode = "de"
title = "Österreich"
theme = "ln-base"

disableKinds = ["taxonomy", "taxonomyTerm"]
enableGitInfo = true

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
  repo = "austria"
